# Generated by Django 5.0.6 on 2024-06-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('client', 'client'), ('seller', 'seller'), ('admin', 'admin')], default='client', max_length=10),
        ),
    ]
